parameters:
#    atlas_front_end.example.class: Atlas\FrontEndBundle\Example

services:
#    atlas_front_end.example:
#        class: %atlas_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
