<?php

namespace AlphaLemon\CmsInstallerBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class InstallerController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AlphaLemon\CmsInstallerBundle\Controller\InstallerController();
        return $instance;
    }
}
